### ISSUE TITLE
cant make it work with ZED mini and d435i

### ISSUE THREAD

**Issue by ceccocats** [engcang/vins-application#1]
Hi @engcang 
Im testing VINS-Fusion CPU with ZED mini, can you ensure you are able to run it?

Im not able to correctly init VINS, I always obtain NaNs:
```
WARNING: Logging before InitGoogleLogging() is written to STDERR
W0814 15:14:59.771003 19283 parameter_block.h:349] Local parameterization Jacobian computation returnedan invalid matrix for x: -nan -nan -nan -nan
 Jacobian matrix : 0nan 0nan 0nan
-nan -nan 0nan
0nan -nan -nan
-nan 0nan -nan
F0814 15:14:59.771054 19283 parameter_block.h:189] Check failed: UpdateLocalParameterizationJacobian() Local parameterization Jacobian computation failed for x: -nan -nan -nan -nan
```

This in my config
<details>
  <summary>zed_imu_config.yaml</summary>

```
%YAML:1.0

#common parameters
#support: 1 imu 1 cam; 1 imu 2 cam: 2 cam; 
imu: 1         
num_of_cam: 1  

imu_topic: "/zed/zed_node/imu/data_raw"
image0_topic: "/zed/zed_node/left/image_rect_color"
image1_topic: "/zed/zed_node/right/image_rect_color"
output_path: "~/output/"

cam0_calib: "cam_pinhole_l.yaml"
cam1_calib: "cam_pinhole_r.yaml"
image_width: 672
image_height: 376
   

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 1   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.

body_T_cam0: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [0.0014846158067664955, -0.9999566394077031, -0.009193215996598725, 0.0026856085760216626,
          0.026265352079174964, 0.009229046866280219, -0.9996124028712818, 0.0009023689144005919,
          0.9996539037067099, 0.0012425773190519185, 0.02627791478681095, 0.0006287860401229842,
          0, 0, 0, 1]
body_T_cam1: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [-0.0016843852880614036, -0.9999562677393219, -0.009199209479474446, -0.06711970546466307,
           0.025674324312040753, 0.009152946405229194, -0.9996284572996227, 0.0022119334059672777,
           0.9996689411586828, -0.0019199429545934121, 0.02565778442752982, 0.0006892909975584863,
           0, 0, 0, 1]

#Multiple thread support
multiple_thread: 8

#feature traker paprameters
max_cnt: 110            # max feature number in feature tracking
min_dist: 18            # min distance between two features 
freq: 0                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1        # ransac threshold (pixel)
show_track: 0          # publish tracking image as topic
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy

#optimization parameters
max_solver_time: 0.045  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 0.1          # accelerometer measurement noise standard deviation. 
gyr_n: 0.01         # gyroscope measurement noise standard deviation.     
acc_w: 0.001        # accelerometer bias random work noise standard deviation.  
gyr_w: 0.0001       # gyroscope bias random work noise standard deviation.     
g_norm: 9.81007     # gravity magnitude

#unsynchronization parameters
estimate_td: 1                      # online estimate time offset between camera and imu
td: -0.04                             # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#loop closure parameters
load_previous_pose_graph: 0        # load and reuse previous pose graph; load from 'pose_graph_save_path'
pose_graph_save_path: "~/output/pose_graph/" # save and load path
save_image: 0                   # save image in pose graph for visualization prupose; you can close this function by setting 0 

```  
</details>

thank you very much,
Francesco

**Comment by engcang** [comment]
> Hi @engcang
> Im testing VINS-Fusion CPU with ZED mini, can you ensure you are able to run it?
> 
> Im not able to correctly init VINS, I always obtain NaNs:
> 
> ```
> WARNING: Logging before InitGoogleLogging() is written to STDERR
> W0814 15:14:59.771003 19283 parameter_block.h:349] Local parameterization Jacobian computation returnedan invalid matrix for x: -nan -nan -nan -nan
>  Jacobian matrix : 0nan 0nan 0nan
> -nan -nan 0nan
> 0nan -nan -nan
> -nan 0nan -nan
> F0814 15:14:59.771054 19283 parameter_block.h:189] Check failed: UpdateLocalParameterizationJacobian() Local parameterization Jacobian computation failed for x: -nan -nan -nan -nan
> ```
> 
> This in my config
> 
> zed_imu_config.yaml
> thank you very much,
> Francesco

@ceccocats 
Hi Ceccocats, 
Yes I could run it at that time with my config files.
It seems that you just copied and pasted my config files and tried to run VINS, didn't you?

1. When I tried to run VINS with realsense d435i using wrong camera calibration parameters, I also obtained NaNs.
I recommend you to calibrate your cameras and IMU again, properly.

2. Your error messages are from Ceres Solver. I think there could be two reasons.
First, the residual( optimization objective function from the paper ) is not feasible within iteration and solving time due to its calibration or IMU/Camera feature matching re-projection errors are too big. So you can try to edit the optimization parameters, which I do not recommend.
Second, as you said, gyroscope bias/accelerometer bias initialization failed due to wrong camera calibration parameters or wrong camera-imu extrinsic parameters.

Can you check your all of parameters again and can you attach all of your config files please?
I recommend you to use Kalibr package and make sure to set your camera's distortion model as 'radtan' rather than equidistant or something else.
Also can you attach all of your terminal output right after you run the VINS and before you get NaNs.

Thank you for your interest for my repository~

Oh by the way, I want to learn how to use 'tkDNN'. Can I use implement 'yolo-v4-tiny ROS version' using tkDNN?? It would be great if possible.

**Comment by engcang** [comment]
@ceccocats 
Ah, also try to run VINS using 0 IMU and 2 cameras by editing config files,
it will help you to debug whether only cameras are calibrated improperly or not.

**Comment by ceccocats** [comment]
The error was a frame dimension issue because your zed launcher was from an old version of zed_wrapper.
I tried my calibration with kalibr and lost the entire afternoon testing with all the possible configs but I always had a lot of drift.
I think that the calibration made with kalibr was poor.
Now I'm starting from the beginning with imu-utils to find the Allan variance of the Imu and then I will recalibrate hoping for better results.
I thinked that using the same sensor it would be easy to have a working VINS but this algorithm is really a mess to make it work.

You used pinhole-equi, why you think radtan is better? Zed mini have a fov of 110 deg so not a proper fisheye.
Do you recommend to use image_rect_color or image_raw_color or image_raw_gray?
Do you think is better imu/data or imu/data_raw?

About tkDNN, you can easily use it as a library.
We use it in several projects with and without ROS.

**Comment by engcang** [comment]
@ceccocats 
Did you make it work so far?

Well, I actually used pinhole-radtan model as here : https://github.com/engcang/vins-application/blob/zed-mini/kalibr-zed/camchain-imucam-Kalibr_data.yaml
But yeah maybe pinhole-equidistant model would be better as it has large fov fisheye camera.

Actually since VINS using zed-mini camera was older than 1 year for me, I almost forgot it, but according to my experience using Intel realsense d435i recently, radtan model showed a lot better result.

And why do you have to use that camera? I recommend you to use other camera, because zed-mini adopted Rolling shutter as here: https://www.stereolabs.com/zed-mini/

The performances of VINS depending on which shutter was really different I remember, so that I moved on to use Pointgrey+IMU sensor or D435i camera.

I recommend imu/data_raw because you are going to calibrate it using imu_utils, without any hardware filter inherent.
For the image, image_raw_color, for the same reason that you are going to calibrate it. 
But since I do not remember it 100% now, please check if there is global shutter image topic for zed-mini first.
If there exist, then you should choose that!

And for what you said - this algorithm is really a mess to make it work 
-> It is true when we are using poor sensor setup, but it is not true when we have proper sensor setup that global shutter camera with proper fov and just any imu. I have taken many advantage using VINS with many setups! But surely I used global shutter camera for all of them.
And yes, I think I could not get good result using large fov cameras including fisheye.

**Comment by ceccocats** [comment]
Im steady because I can't print the April target and with the screen is not working well when tilting on the side.
Im using zed mini because is what I have... I also have D435 (without imu) but I can use it with an xsens IMU.
Do you think is better this setup?

I have seen that VINS-Mono have a rolling shutter feature, have you tried it?
Also kalibr have a rolling shutter calibration.

Thank you for your help

**Comment by engcang** [comment]
@ceccocats 

Oh man I do not recommend you to use April tag with screen. You should print it and fix it on the wall. It is ok if you only can print it on small A4 paper. But make sure that the target april.yaml file's config values are correct.

I think D435  + Xsense will be much better.
You should fix them using strong bond or tape to fix extrinsic parameter between them.
and use infra1/image_rect_raw topics and infra2 for cameras. Because only infra are with global shutter. And do not forget to turn off IR pattern emitter. you can refer my other branch in this repo.

**Comment by ceccocats** [comment]
I borrowed a D435i and calibrated it, but I am not sure the calibration is good.
The camera/camera calib seems good (even if I have an higher error) but the camera/imu is a totally different from yours
I have this BIG errors that I cant explain; 
Before kalibr I made the imu calibration with the realsense tool and computed the Allan variance with imu-utils

[results-cam-homesebDocumentsvokalibr-cded435calib.txt](https://github.com/engcang/vins-application/files/5093139/results-cam-homesebDocumentsvokalibr-cded435calib.txt)
[results-imucam-homesebDocumentsvokalibr-cded435calib.txt](https://github.com/engcang/vins-application/files/5093140/results-imucam-homesebDocumentsvokalibr-cded435calib.txt)

**Comment by engcang** [comment]
@ceccocats 
Yeah your camera calibrations look greater than mine. Also IMU Allan values look good.
But cam-imu seems weird. 

Calibration results
===================
Reprojection error squarred (cam0):  mean 5.65965943919, median 0.623765766622, std: 68.0231890053
Reprojection error squarred (cam1):  mean 4.65020168339, median 0.544280617995, std: 52.6817094527
Gyro error squarred (imu0):          mean 237.616579499, median 4.14097713844, std: 1308.89556261
Accelerometer error squarred (imu0): mean 12.5063602261, median 3.22671477274, std: 31.4982037758

I don't understand why errors are so big..

1. Can you try to compare your IMU behavior with this: https://github.com/IntelRealSense/librealsense/issues/7103#issuecomment-675284211

I am not sure if mine worked like that at that time.

2. And did you set the Gyro+Accelerometer united method in the rs_camera.launch file?
  <arg name="unite_imu_method"      default="linear_interpolation"/>

3. Maybe this is because of recent version of realsense SDK? .... hmm but your Allan data is ok...
4. I think you well-moved your camera like here: https://github.com/ethz-asl/kalibr#tutorial-imu-camera-calibration
right??

Now to be honest I do not know why your cam-imu calibration is bad like that... Hmmm..
Sorry about that!

**Comment by ceccocats** [comment]
I definitely have the IMU behaviour you linked, but I don't get if it is normal or my unit fault.
Also I setted united_method to linear_interpolation but the /camera/imu framerate is 200 Hz and not 400 Hz.

**Comment by ceccocats** [comment]
I recalibrated using [rs4se](https://github.com/chutsu/rs4se) for reading the sensor
And now the results are much better:
[results-cam-homesebDocumentsvokalibr-cded435calibrs4se.txt](https://github.com/engcang/vins-application/files/5096485/results-cam-homesebDocumentsvokalibr-cded435calibrs4se.txt)
[results-imucam-homesebDocumentsvokalibr-cded435calibrs4se.txt](https://github.com/engcang/vins-application/files/5096486/results-imucam-homesebDocumentsvokalibr-cded435calibrs4se.txt)

Still I dont get why you have a different TF than me, maybe it is a kalibr configuration? My orientations are wrong
here are yours and my estrinsics visualized, mine is on the right:
![Screenshot from 2020-08-19 15-45-44](https://user-images.githubusercontent.com/11562617/90642823-2a5a6c80-e233-11ea-91b3-2eb55771c335.png)

**Comment by engcang** [comment]
@ceccocats 
Well I have no idea hahaha

Maybe I use a lot older version of libRealsense SDK and ROS version? That could be a reason, to make different transformation.
Or maybe you used rs4se???

Well, anyway, now your calibration seems perfect. So regardless of the TF, I think your VINS-Fusion should work well with your new camera calibration parameters and camera-IMU extrinsic parameters!

So try it first, and then let me hear good news from you.

**Comment by ceccocats** [comment]
I obtained more or less the same tfs with realsense, so I don't think rs4se is the problem. I will also try with older sdk I should refer to the one you used on Xavier?

with imu and 1 cam it works ok, but only with estimate_extrinsic=1.
Even if it works ok if I roll the sensor (even slow) of 90 deg (with the connector facing up or down) it start to drift.
Do you remember an issue like that?

If I try with 2 cam it wont work I think because of the incorrect kalibr result.
Maybe the issue it could be the initial calibration with the realsense tool

**Comment by engcang** [comment]
@ceccocats

I have not every tried roll 90 deg. I am using VINS for just normal movement of mobile robots and drones.

I also recommend to set estimate_extrinsic as 1.

When setting 2 cameras, yeah, you should give correct body_t_cam parameters.
I am also still confused about body_t_cam transformation and cam_t_body transformation.

I think we should give the transposed value into body_t_cam parameter from result of Kalibr.

ex: Kalibr's result : T_cam_body
VINS's config file : body_T_cam
So I guess they should be transposed.
simply, get the inverse matrix of 4x4 result matrix of Kalibr and then give it into VINS's yaml file.

and please move smoothly at the first time of initializing procedure for VINS.

**Comment by ceccocats** [comment]
I think an issue can be that Im using kalibr-cde (the prebuilt package)
Because im recalibrating with the master branch of kalibr compiled from source and as of now I obtained an even better camera calibration, now is calibrating the camera-imu.
The problem is that is deadly slow.

I really appreciate your help, thank you very much.
I hope this issue will be useful for everyone with the same problem

**Comment by engcang** [comment]
@ceccocats 
Yeah. Don't forget to build your Kalibr package with **Release** buildtype by
~~~shell
  $ catkin build kalibr -DCMAKE_BUILD_TYPE=Release
~~~

This will make the node run faster I believe.

**Comment by engcang** [comment]
@ceccocats 
Any news for this issue? Did you make it work?
I recently had a chance to test VINS-Fusion (stereo) with Intel D435i and here is the [result clip](https://youtu.be/Gx0PSMCeR1g), if you are interested in yet.
