### ISSUE TITLE
How to use d435i with Khadas VIM3?

### ISSUE THREAD

**Issue by Michael0126** [engcang/vins-application#14]
How to find the device(realsense d435i) with khadas VIM3? I have found that libreasense doesn't support the ubuntu 4.9 kernel. Which version of librealsense needs to be installed？

**Comment by engcang** [comment]
Hi.
In the official page's supported platform list, there is no 4.9 kernel on the list. 
However, I am pretty sure that 4.9 kernel is naturally supported with any `librealsense` version, since I also just installed normal `librealsense` on `Khadas VIM3` and `NVIDIA Jetson` boards which are using 4.9 kernels.

To clarify, I installed `2.45` version when I tested with the boards.
