### ISSUE TITLE
Using vins on OAK-D-PRO

### ISSUE THREAD

**Issue by ahjcahkl** [engcang/vins-application#19]
Hi, I am a beginner at VINS. We are currently trying to implement vins using Oak-d-pro. The environment I am using is Ubuntu 20.04, ROS 1 nonetic, and opencv 4. I feel quite confused after following the code configuration above. I am not sure how to establish a connection with the oak-ros simple mentioned under the oak-d branch, and how to run the currently configured vins code to achieve the effect you demonstrated. If it won't take up too much of your time, could you please guide me on what I should do to run it after configuring the config.yaml and Calibration data under the branch.Thanks a lot!

**Comment by ahjcahkl** [comment]
Should oakd ros simple be installed in the same src folder as this Vins?

**Comment by ahjcahkl** [comment]
At the same time, I am also confused about the code in vins-application/vins_estimator/launch/vins_rviz.launch, with only three lines, which makes me unsure if it can run properly.

**Comment by engcang** [comment]
@ahjcahkl 

1. Install VIO algorithm you want, set the config files properly - it usually contains the topic names of images and IMU. So type the output from oakd ROS node there.
2. Then run the oakd ROS node and VIO algorithm node. They do not have to be in the same folder but just built properly so that they can be run as executable nodes.
3. vins_estimator/launch/vins_rviz.launch is for the VINS-Fusion algorithm and only for running the Rviz node. So you can just ignore this.
4. I linked original repositories here - https://github.com/engcang/vins-application/?tab=readme-ov-file#0-algorithms and check out how to run the each algorithm from the official repositories, please.
5. This repository mainly focuses on build process and trouble shooting plus applications of many VIO algorithms as written here -https://github.com/engcang/vins-application?tab=readme-ov-file#mainly-focused-on-build-process-and-explanation but not any official repositories of VIO algorithms listed. So you should check official repository together. 
6. Please note again, this repository mainly focuses on build process and trouble shooting and comparisons or applications of VIOs.
